[2024-07-09T09:18:42.144+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T09:18:42.155+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T09:18:42.155+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T09:18:42.170+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-07-08 00:00:00+00:00
[2024-07-09T09:18:42.179+0000] {standard_task_runner.py:60} INFO - Started process 1524 to run task
[2024-07-09T09:18:42.182+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpzejm5cmp']
[2024-07-09T09:18:42.183+0000] {standard_task_runner.py:88} INFO - Job 99: Subtask publish.customer_metrics_run
[2024-07-09T09:18:42.231+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-07-08T00:00:00+00:00 [running]> on host 3726baa263d6
[2024-07-09T09:18:42.314+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-09T09:18:42.316+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmptl3pu22y from /opt/airflow/include/dbt/fraud
[2024-07-09T09:18:42.323+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-07-09T09:18:42.324+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmptl3pu22y
[2024-07-09T09:18:42.325+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-07-09T09:18:42.325+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-09T09:18:42.326+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-07-09T09:18:42.338+0000] {subprocess.py:84} INFO - Command output:
[2024-07-09T09:18:43.618+0000] {subprocess.py:94} INFO - [0m09:18:43  Running with dbt=1.8.1
[2024-07-09T09:18:44.449+0000] {subprocess.py:94} INFO - [0m09:18:44  Registered adapter: snowflake=1.8.2
[2024-07-09T09:18:44.485+0000] {subprocess.py:94} INFO - [0m09:18:44  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-07-09T09:18:45.755+0000] {subprocess.py:94} INFO - [0m09:18:45  Found 3 models, 444 macros
[2024-07-09T09:18:45.756+0000] {subprocess.py:94} INFO - [0m09:18:45
[2024-07-09T09:18:47.049+0000] {subprocess.py:94} INFO - [0m09:18:47  Concurrency: 1 threads (target='dev')
[2024-07-09T09:18:47.050+0000] {subprocess.py:94} INFO - [0m09:18:47
[2024-07-09T09:18:47.058+0000] {subprocess.py:94} INFO - [0m09:18:47  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]
[2024-07-09T09:18:47.321+0000] {subprocess.py:94} INFO - [0m09:18:47  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [[31mERROR[0m in 0.26s]
[2024-07-09T09:18:47.324+0000] {subprocess.py:94} INFO - [0m09:18:47
[2024-07-09T09:18:47.325+0000] {subprocess.py:94} INFO - [0m09:18:47  Finished running 1 table model in 0 hours 0 minutes and 1.57 seconds (1.57s).
[2024-07-09T09:18:47.365+0000] {subprocess.py:94} INFO - [0m09:18:47
[2024-07-09T09:18:47.366+0000] {subprocess.py:94} INFO - [0m09:18:47  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-09T09:18:47.366+0000] {subprocess.py:94} INFO - [0m09:18:47
[2024-07-09T09:18:47.367+0000] {subprocess.py:94} INFO - [0m09:18:47    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-07-09T09:18:47.367+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-07-09T09:18:47.368+0000] {subprocess.py:94} INFO -   syntax error line 35 at position 23 unexpected ';'.
[2024-07-09T09:18:47.369+0000] {subprocess.py:94} INFO -   compiled Code at target/run/fraud/models/customer_metrics.sql
[2024-07-09T09:18:47.370+0000] {subprocess.py:94} INFO - [0m09:18:47
[2024-07-09T09:18:47.371+0000] {subprocess.py:94} INFO - [0m09:18:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-07-09T09:18:48.934+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-07-09T09:18:48.954+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-09T09:18:48.955+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-09T09:18:48.968+0000] {local.py:252} INFO - Inlets: []
[2024-07-09T09:18:48.969+0000] {local.py:253} INFO - Outlets: []
[2024-07-09T09:18:48.970+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-07-09T09:18:48.999+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-07-09 00:00:00+00:00, run_after=2024-07-10 00:00:00+00:00
[2024-07-09T09:18:49.041+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:18:43  Running with dbt=1.8.1', '\x1b[0m09:18:44  Registered adapter: snowflake=1.8.2', '\x1b[0m09:18:44  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:18:45  Found 3 models, 444 macros', '\x1b[0m09:18:45', "\x1b[0m09:18:47  Concurrency: 1 threads (target='dev')", '\x1b[0m09:18:47', '\x1b[0m09:18:47  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:18:47  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.26s]', '\x1b[0m09:18:47', '\x1b[0m09:18:47  Finished running 1 table model in 0 hours 0 minutes and 1.57 seconds (1.57s).', '\x1b[0m09:18:47', '\x1b[0m09:18:47  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:18:47', '\x1b[0m09:18:47    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 35 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:18:47', '\x1b[0m09:18:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-07-09T09:18:49.045+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20240708T000000, start_date=20240709T091842, end_date=20240709T091849
[2024-07-09T09:18:49.061+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 99 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:18:43  Running with dbt=1.8.1', '\x1b[0m09:18:44  Registered adapter: snowflake=1.8.2', '\x1b[0m09:18:44  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:18:45  Found 3 models, 444 macros', '\x1b[0m09:18:45', "\x1b[0m09:18:47  Concurrency: 1 threads (target='dev')", '\x1b[0m09:18:47', '\x1b[0m09:18:47  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:18:47  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.26s]', '\x1b[0m09:18:47', '\x1b[0m09:18:47  Finished running 1 table model in 0 hours 0 minutes and 1.57 seconds (1.57s).', '\x1b[0m09:18:47', '\x1b[0m09:18:47  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:18:47', '\x1b[0m09:18:47    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 35 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:18:47', '\x1b[0m09:18:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 1524)
[2024-07-09T09:18:49.109+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T09:18:49.137+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
