[2024-07-09T09:40:51.355+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:39:16.724470+00:00 [queued]>
[2024-07-09T09:40:51.368+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:39:16.724470+00:00 [queued]>
[2024-07-09T09:40:51.369+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T09:40:51.385+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-07-09 09:39:16.724470+00:00
[2024-07-09T09:40:51.391+0000] {standard_task_runner.py:60} INFO - Started process 2255 to run task
[2024-07-09T09:40:51.395+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'manual__2024-07-09T09:39:16.724470+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmp7lo8xy48']
[2024-07-09T09:40:51.396+0000] {standard_task_runner.py:88} INFO - Job 149: Subtask publish.customer_metrics_run
[2024-07-09T09:40:51.447+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:39:16.724470+00:00 [running]> on host 3726baa263d6
[2024-07-09T09:40:51.523+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T09:39:16.724470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T09:39:16.724470+00:00'
[2024-07-09T09:40:51.525+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmp_wwir01y from /opt/airflow/include/dbt/fraud
[2024-07-09T09:40:51.529+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-07-09T09:40:51.530+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmp_wwir01y
[2024-07-09T09:40:51.532+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-07-09T09:40:51.533+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-09T09:40:51.533+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-07-09T09:40:51.544+0000] {subprocess.py:84} INFO - Command output:
[2024-07-09T09:40:52.897+0000] {subprocess.py:94} INFO - [0m09:40:52  Running with dbt=1.8.1
[2024-07-09T09:40:53.759+0000] {subprocess.py:94} INFO - [0m09:40:53  Registered adapter: snowflake=1.8.2
[2024-07-09T09:40:53.789+0000] {subprocess.py:94} INFO - [0m09:40:53  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-07-09T09:40:55.128+0000] {subprocess.py:94} INFO - [0m09:40:55  Found 3 models, 444 macros
[2024-07-09T09:40:55.130+0000] {subprocess.py:94} INFO - [0m09:40:55
[2024-07-09T09:40:55.979+0000] {subprocess.py:94} INFO - [0m09:40:55  Concurrency: 1 threads (target='dev')
[2024-07-09T09:40:55.979+0000] {subprocess.py:94} INFO - [0m09:40:55
[2024-07-09T09:40:55.985+0000] {subprocess.py:94} INFO - [0m09:40:55  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]
[2024-07-09T09:40:56.259+0000] {subprocess.py:94} INFO - [0m09:40:56  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [[31mERROR[0m in 0.27s]
[2024-07-09T09:40:56.262+0000] {subprocess.py:94} INFO - [0m09:40:56
[2024-07-09T09:40:56.263+0000] {subprocess.py:94} INFO - [0m09:40:56  Finished running 1 table model in 0 hours 0 minutes and 1.13 seconds (1.13s).
[2024-07-09T09:40:56.295+0000] {subprocess.py:94} INFO - [0m09:40:56
[2024-07-09T09:40:56.296+0000] {subprocess.py:94} INFO - [0m09:40:56  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-09T09:40:56.297+0000] {subprocess.py:94} INFO - [0m09:40:56
[2024-07-09T09:40:56.298+0000] {subprocess.py:94} INFO - [0m09:40:56    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-07-09T09:40:56.298+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-07-09T09:40:56.299+0000] {subprocess.py:94} INFO -   syntax error line 25 at position 23 unexpected ';'.
[2024-07-09T09:40:56.300+0000] {subprocess.py:94} INFO -   compiled Code at target/run/fraud/models/customer_metrics.sql
[2024-07-09T09:40:56.300+0000] {subprocess.py:94} INFO - [0m09:40:56
[2024-07-09T09:40:56.301+0000] {subprocess.py:94} INFO - [0m09:40:56  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-07-09T09:40:57.647+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-07-09T09:40:57.664+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-09T09:40:57.665+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-09T09:40:57.677+0000] {local.py:252} INFO - Inlets: []
[2024-07-09T09:40:57.680+0000] {local.py:253} INFO - Outlets: []
[2024-07-09T09:40:57.681+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-07-09T09:40:57.711+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-07-09 00:00:00+00:00, run_after=2024-07-10 00:00:00+00:00
[2024-07-09T09:40:57.753+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:40:52  Running with dbt=1.8.1', '\x1b[0m09:40:53  Registered adapter: snowflake=1.8.2', '\x1b[0m09:40:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:40:55  Found 3 models, 444 macros', '\x1b[0m09:40:55', "\x1b[0m09:40:55  Concurrency: 1 threads (target='dev')", '\x1b[0m09:40:55', '\x1b[0m09:40:55  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:40:56  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.27s]', '\x1b[0m09:40:56', '\x1b[0m09:40:56  Finished running 1 table model in 0 hours 0 minutes and 1.13 seconds (1.13s).', '\x1b[0m09:40:56', '\x1b[0m09:40:56  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:40:56', '\x1b[0m09:40:56    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 25 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:40:56', '\x1b[0m09:40:56  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-07-09T09:40:57.757+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20240709T093916, start_date=20240709T094051, end_date=20240709T094057
[2024-07-09T09:40:57.773+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 149 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:40:52  Running with dbt=1.8.1', '\x1b[0m09:40:53  Registered adapter: snowflake=1.8.2', '\x1b[0m09:40:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:40:55  Found 3 models, 444 macros', '\x1b[0m09:40:55', "\x1b[0m09:40:55  Concurrency: 1 threads (target='dev')", '\x1b[0m09:40:55', '\x1b[0m09:40:55  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:40:56  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.27s]', '\x1b[0m09:40:56', '\x1b[0m09:40:56  Finished running 1 table model in 0 hours 0 minutes and 1.13 seconds (1.13s).', '\x1b[0m09:40:56', '\x1b[0m09:40:56  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:40:56', '\x1b[0m09:40:56    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 25 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:40:56', '\x1b[0m09:40:56  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 2255)
[2024-07-09T09:40:57.790+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T09:40:57.811+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
