[2024-07-09T09:37:02.344+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:35:02.454752+00:00 [queued]>
[2024-07-09T09:37:02.356+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:35:02.454752+00:00 [queued]>
[2024-07-09T09:37:02.357+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T09:37:02.372+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-07-09 09:35:02.454752+00:00
[2024-07-09T09:37:02.381+0000] {standard_task_runner.py:60} INFO - Started process 1569 to run task
[2024-07-09T09:37:02.385+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'manual__2024-07-09T09:35:02.454752+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmptmrgv2_1']
[2024-07-09T09:37:02.387+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask publish.customer_metrics_run
[2024-07-09T09:37:02.442+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-07-09T09:35:02.454752+00:00 [running]> on host 3726baa263d6
[2024-07-09T09:37:02.525+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T09:35:02.454752+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T09:35:02.454752+00:00'
[2024-07-09T09:37:02.527+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpydwe52qy from /opt/airflow/include/dbt/fraud
[2024-07-09T09:37:02.530+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-07-09T09:37:02.531+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmpydwe52qy
[2024-07-09T09:37:02.532+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-07-09T09:37:02.532+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-09T09:37:02.533+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-07-09T09:37:02.548+0000] {subprocess.py:84} INFO - Command output:
[2024-07-09T09:37:03.896+0000] {subprocess.py:94} INFO - [0m09:37:03  Running with dbt=1.8.1
[2024-07-09T09:37:04.773+0000] {subprocess.py:94} INFO - [0m09:37:04  Registered adapter: snowflake=1.8.2
[2024-07-09T09:37:04.807+0000] {subprocess.py:94} INFO - [0m09:37:04  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-07-09T09:37:06.185+0000] {subprocess.py:94} INFO - [0m09:37:06  Found 3 models, 444 macros
[2024-07-09T09:37:06.186+0000] {subprocess.py:94} INFO - [0m09:37:06
[2024-07-09T09:37:08.136+0000] {subprocess.py:94} INFO - [0m09:37:08  Concurrency: 1 threads (target='dev')
[2024-07-09T09:37:08.136+0000] {subprocess.py:94} INFO - [0m09:37:08
[2024-07-09T09:37:08.145+0000] {subprocess.py:94} INFO - [0m09:37:08  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]
[2024-07-09T09:37:08.480+0000] {subprocess.py:94} INFO - [0m09:37:08  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [[31mERROR[0m in 0.33s]
[2024-07-09T09:37:08.483+0000] {subprocess.py:94} INFO - [0m09:37:08
[2024-07-09T09:37:08.484+0000] {subprocess.py:94} INFO - [0m09:37:08  Finished running 1 table model in 0 hours 0 minutes and 2.30 seconds (2.30s).
[2024-07-09T09:37:08.516+0000] {subprocess.py:94} INFO - [0m09:37:08
[2024-07-09T09:37:08.518+0000] {subprocess.py:94} INFO - [0m09:37:08  [31mCompleted with 1 error and 0 warnings:[0m
[2024-07-09T09:37:08.519+0000] {subprocess.py:94} INFO - [0m09:37:08
[2024-07-09T09:37:08.524+0000] {subprocess.py:94} INFO - [0m09:37:08    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-07-09T09:37:08.527+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-07-09T09:37:08.528+0000] {subprocess.py:94} INFO -   syntax error line 35 at position 23 unexpected ';'.
[2024-07-09T09:37:08.528+0000] {subprocess.py:94} INFO -   compiled Code at target/run/fraud/models/customer_metrics.sql
[2024-07-09T09:37:08.530+0000] {subprocess.py:94} INFO - [0m09:37:08
[2024-07-09T09:37:08.539+0000] {subprocess.py:94} INFO - [0m09:37:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-07-09T09:37:10.028+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-07-09T09:37:10.042+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-09T09:37:10.043+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-09T09:37:10.050+0000] {local.py:252} INFO - Inlets: []
[2024-07-09T09:37:10.051+0000] {local.py:253} INFO - Outlets: []
[2024-07-09T09:37:10.052+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-07-09T09:37:10.080+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-07-09 00:00:00+00:00, run_after=2024-07-10 00:00:00+00:00
[2024-07-09T09:37:10.119+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:37:03  Running with dbt=1.8.1', '\x1b[0m09:37:04  Registered adapter: snowflake=1.8.2', '\x1b[0m09:37:04  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:37:06  Found 3 models, 444 macros', '\x1b[0m09:37:06', "\x1b[0m09:37:08  Concurrency: 1 threads (target='dev')", '\x1b[0m09:37:08', '\x1b[0m09:37:08  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:37:08  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.33s]', '\x1b[0m09:37:08', '\x1b[0m09:37:08  Finished running 1 table model in 0 hours 0 minutes and 2.30 seconds (2.30s).', '\x1b[0m09:37:08', '\x1b[0m09:37:08  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:37:08', '\x1b[0m09:37:08    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 35 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:37:08', '\x1b[0m09:37:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-07-09T09:37:10.124+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20240709T093502, start_date=20240709T093702, end_date=20240709T093710
[2024-07-09T09:37:10.139+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 142 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m09:37:03  Running with dbt=1.8.1', '\x1b[0m09:37:04  Registered adapter: snowflake=1.8.2', '\x1b[0m09:37:04  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m09:37:06  Found 3 models, 444 macros', '\x1b[0m09:37:06', "\x1b[0m09:37:08  Concurrency: 1 threads (target='dev')", '\x1b[0m09:37:08', '\x1b[0m09:37:08  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m09:37:08  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.33s]', '\x1b[0m09:37:08', '\x1b[0m09:37:08  Finished running 1 table model in 0 hours 0 minutes and 2.30 seconds (2.30s).', '\x1b[0m09:37:08', '\x1b[0m09:37:08  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m09:37:08', '\x1b[0m09:37:08    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 35 at position 23 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m09:37:08', '\x1b[0m09:37:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 1569)
[2024-07-09T09:37:10.170+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T09:37:10.189+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
