[2024-07-09T11:02:12.782+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.audit_labeled_transactions manual__2024-07-09T10:59:55.341383+00:00 [queued]>
[2024-07-09T11:02:12.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.audit_labeled_transactions manual__2024-07-09T10:59:55.341383+00:00 [queued]>
[2024-07-09T11:02:12.804+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T11:02:12.833+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonExternalDecoratedOperator): audit_labeled_transactions> on 2024-07-09 10:59:55.341383+00:00
[2024-07-09T11:02:12.847+0000] {standard_task_runner.py:60} INFO - Started process 4850 to run task
[2024-07-09T11:02:12.854+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'audit_labeled_transactions', 'manual__2024-07-09T10:59:55.341383+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpl2h5yey0']
[2024-07-09T11:02:12.859+0000] {standard_task_runner.py:88} INFO - Job 183: Subtask audit_labeled_transactions
[2024-07-09T11:02:12.980+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.audit_labeled_transactions manual__2024-07-09T10:59:55.341383+00:00 [running]> on host 428c62206da4
[2024-07-09T11:02:13.175+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='audit_labeled_transactions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T10:59:55.341383+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T10:59:55.341383+00:00'
[2024-07-09T11:02:13.264+0000] {python.py:913} WARNING - When checking for Airflow installed in virtual environment got Command '['/opt/airflow/soda_venv/bin/python', '-c', 'from airflow import __version__; print(__version__)']' returned non-zero exit status 1.
[2024-07-09T11:02:13.266+0000] {python.py:914} WARNING - This means that Airflow is not properly installed by  /opt/airflow/soda_venv/bin/python. Airflow context keys will not be available. Please Install Airflow 2.8.2 in your environment to access them.
[2024-07-09T11:02:13.374+0000] {process_utils.py:182} INFO - Executing cmd: /opt/airflow/soda_venv/bin/python /tmp/venv-callunyrs5e5/script.py /tmp/venv-callunyrs5e5/script.in /tmp/venv-callunyrs5e5/script.out /tmp/venv-callunyrs5e5/string_args.txt /tmp/venv-callunyrs5e5/termination.log
[2024-07-09T11:02:13.395+0000] {process_utils.py:186} INFO - Output:
[2024-07-09T11:02:17.598+0000] {process_utils.py:190} INFO - Running Soda Scan ...
[2024-07-09T11:02:17.602+0000] {process_utils.py:190} INFO - INFO   | Soda Core 3.2.2
[2024-07-09T11:02:17.603+0000] {process_utils.py:190} INFO - DEBUG  | Reading configuration file "include/soda/configuration.yml"
[2024-07-09T11:02:17.607+0000] {process_utils.py:190} INFO - DEBUG  | Reading SodaCL file "include/soda/checks/tables/labeled_transactions.yml"
[2024-07-09T11:02:17.611+0000] {process_utils.py:190} INFO - DEBUG  | Reading SodaCL file "include/soda/checks/tables/customer_transactions.yml"
[2024-07-09T11:02:17.613+0000] {process_utils.py:190} INFO - DEBUG  | Scan execution starts
[2024-07-09T11:02:17.615+0000] {process_utils.py:190} INFO - DEBUG  | Query staging.customer_transactions.aggregation[0]:
[2024-07-09T11:02:17.618+0000] {process_utils.py:190} INFO - SELECT
[2024-07-09T11:02:17.621+0000] {process_utils.py:190} INFO -   COUNT(*),
[2024-07-09T11:02:17.623+0000] {process_utils.py:190} INFO -   COUNT(CASE WHEN transaction_id IS NULL THEN 1 END),
[2024-07-09T11:02:17.625+0000] {process_utils.py:190} INFO -   COUNT(CASE WHEN user_id IS NULL THEN 1 END),
[2024-07-09T11:02:17.628+0000] {process_utils.py:190} INFO -   COUNT(CASE WHEN transaction_date IS NULL THEN 1 END),
[2024-07-09T11:02:17.631+0000] {process_utils.py:190} INFO -   COUNT(CASE WHEN amount IS NULL THEN 1 END)
[2024-07-09T11:02:17.635+0000] {process_utils.py:190} INFO - FROM AIRBYTE_DATABASE.STAGING.customer_transactions
[2024-07-09T11:02:17.638+0000] {process_utils.py:190} INFO - DEBUG  | Query staging.customer_transactions.transaction_id.duplicate_count:
[2024-07-09T11:02:17.639+0000] {process_utils.py:190} INFO - 
[2024-07-09T11:02:17.645+0000] {process_utils.py:190} INFO - WITH frequencies AS (
[2024-07-09T11:02:17.647+0000] {process_utils.py:190} INFO -     SELECT COUNT(*) AS frequency
[2024-07-09T11:02:17.656+0000] {process_utils.py:190} INFO -     FROM AIRBYTE_DATABASE.STAGING.customer_transactions
[2024-07-09T11:02:17.662+0000] {process_utils.py:190} INFO -     WHERE transaction_id IS NOT NULL
[2024-07-09T11:02:17.664+0000] {process_utils.py:190} INFO -     GROUP BY transaction_id)
[2024-07-09T11:02:17.681+0000] {process_utils.py:190} INFO - SELECT COUNT(*)
[2024-07-09T11:02:17.684+0000] {process_utils.py:190} INFO - FROM frequencies
[2024-07-09T11:02:17.687+0000] {process_utils.py:190} INFO - WHERE frequency > 1
[2024-07-09T11:02:17.692+0000] {process_utils.py:190} INFO - DEBUG  | Query staging.customer_transactions.duplicate_count[transaction_id].failed_rows.aggregated:
[2024-07-09T11:02:17.703+0000] {process_utils.py:190} INFO - 
[2024-07-09T11:02:17.705+0000] {process_utils.py:190} INFO - WITH frequencies AS (
[2024-07-09T11:02:17.706+0000] {process_utils.py:190} INFO -     SELECT transaction_id, COUNT(*) AS frequency
[2024-07-09T11:02:17.707+0000] {process_utils.py:190} INFO -     FROM AIRBYTE_DATABASE.STAGING.customer_transactions
[2024-07-09T11:02:17.709+0000] {process_utils.py:190} INFO -     WHERE transaction_id IS NOT NULL
[2024-07-09T11:02:17.711+0000] {process_utils.py:190} INFO -     GROUP BY transaction_id)
[2024-07-09T11:02:17.713+0000] {process_utils.py:190} INFO - SELECT *
[2024-07-09T11:02:17.714+0000] {process_utils.py:190} INFO - FROM frequencies
[2024-07-09T11:02:17.717+0000] {process_utils.py:190} INFO - WHERE frequency > 1
[2024-07-09T11:02:17.720+0000] {process_utils.py:190} INFO - ORDER BY frequency DESC
[2024-07-09T11:02:17.725+0000] {process_utils.py:190} INFO - LIMIT 100
[2024-07-09T11:02:17.728+0000] {process_utils.py:190} INFO - DEBUG  | Query staging.customer_transactions.schema[customer_transactions]:
[2024-07-09T11:02:17.730+0000] {process_utils.py:190} INFO - SELECT column_name, data_type, is_nullable
[2024-07-09T11:02:17.732+0000] {process_utils.py:190} INFO - FROM information_schema.columns
[2024-07-09T11:02:17.734+0000] {process_utils.py:190} INFO - WHERE upper(table_name) = 'CUSTOMER_TRANSACTIONS'
[2024-07-09T11:02:17.737+0000] {process_utils.py:190} INFO -   AND upper(table_catalog) = 'AIRBYTE_DATABASE'
[2024-07-09T11:02:17.739+0000] {process_utils.py:190} INFO -   AND upper(table_schema) = 'STAGING'
[2024-07-09T11:02:17.741+0000] {process_utils.py:190} INFO - ORDER BY ORDINAL_POSITION
[2024-07-09T11:02:17.743+0000] {process_utils.py:190} INFO - INFO   | Scan summary:
[2024-07-09T11:02:17.746+0000] {process_utils.py:190} INFO - DEBUG  | 4/4 queries OK
[2024-07-09T11:02:17.747+0000] {process_utils.py:190} INFO - DEBUG  |   staging.customer_transactions.aggregation[0] [OK] 0:00:00.107049
[2024-07-09T11:02:17.749+0000] {process_utils.py:190} INFO - DEBUG  |   staging.customer_transactions.transaction_id.duplicate_count [OK] 0:00:00.103484
[2024-07-09T11:02:17.751+0000] {process_utils.py:190} INFO - DEBUG  |   staging.customer_transactions.duplicate_count[transaction_id].failed_rows.aggregated [OK] 0:00:00.073826
[2024-07-09T11:02:17.753+0000] {process_utils.py:190} INFO - DEBUG  |   staging.customer_transactions.schema[customer_transactions] [OK] 0:00:00.874049
[2024-07-09T11:02:17.755+0000] {process_utils.py:190} INFO - INFO   | 12/14 checks PASSED:
[2024-07-09T11:02:17.757+0000] {process_utils.py:190} INFO - INFO   |     customer_transactions in staging
[2024-07-09T11:02:17.758+0000] {process_utils.py:190} INFO - INFO   |       Schema Check [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.760+0000] {process_utils.py:190} INFO - INFO   |         schema_measured = [_AIRBYTE_RAW_ID TEXT, _AIRBYTE_EXTRACTED_AT TIMESTAMP_TZ, _AIRBYTE_META VARIANT, AMOUNT FLOAT, USER_ID NUMBER, TRANSACTION_ID NUMBER, TRANSACTION_DATE TEXT, _AB_SOURCE_FILE_URL TEXT, _AB_SOURCE_FILE_LAST_MODIFIED TEXT]
[2024-07-09T11:02:17.761+0000] {process_utils.py:190} INFO - INFO   |       Schema Check [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.762+0000] {process_utils.py:190} INFO - INFO   |         schema_measured = [_AIRBYTE_RAW_ID TEXT, _AIRBYTE_EXTRACTED_AT TIMESTAMP_TZ, _AIRBYTE_META VARIANT, AMOUNT FLOAT, USER_ID NUMBER, TRANSACTION_ID NUMBER, TRANSACTION_DATE TEXT, _AB_SOURCE_FILE_URL TEXT, _AB_SOURCE_FILE_LAST_MODIFIED TEXT]
[2024-07-09T11:02:17.763+0000] {process_utils.py:190} INFO - INFO   |       Duplicate transaction IDs [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.764+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.766+0000] {process_utils.py:190} INFO - INFO   |       Transaction IDs cannot be null [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.767+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.768+0000] {process_utils.py:190} INFO - INFO   |       Duplicate transaction ids [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.769+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.770+0000] {process_utils.py:190} INFO - INFO   |       Transactions ids missing in customer_transactions [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.771+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.772+0000] {process_utils.py:190} INFO - INFO   |       User IDs cannot be null [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.773+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.774+0000] {process_utils.py:190} INFO - INFO   |       User ids missing in customer_transactions [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.775+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.776+0000] {process_utils.py:190} INFO - INFO   |       Transaction date cannot be null [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.777+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.778+0000] {process_utils.py:190} INFO - INFO   |       transaction_date missing in customer_transactions [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.779+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.779+0000] {process_utils.py:190} INFO - INFO   |       Amount cannot be null [include/soda/checks/tables/labeled_transactions.yml] [PASSED]
[2024-07-09T11:02:17.780+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.782+0000] {process_utils.py:190} INFO - INFO   |       amount missing in customer_transactions [include/soda/checks/tables/customer_transactions.yml] [PASSED]
[2024-07-09T11:02:17.783+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.784+0000] {process_utils.py:190} INFO - INFO   | 2/14 checks FAILED:
[2024-07-09T11:02:17.785+0000] {process_utils.py:190} INFO - INFO   |     customer_transactions in staging
[2024-07-09T11:02:17.786+0000] {process_utils.py:190} INFO - INFO   |       Table is empty [include/soda/checks/tables/labeled_transactions.yml] [FAILED]
[2024-07-09T11:02:17.787+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.788+0000] {process_utils.py:190} INFO - INFO   |       Table is empty [include/soda/checks/tables/customer_transactions.yml] [FAILED]
[2024-07-09T11:02:17.789+0000] {process_utils.py:190} INFO - INFO   |         check_value: 0
[2024-07-09T11:02:17.789+0000] {process_utils.py:190} INFO - INFO   | Oops! 2 failures. 0 warnings. 0 errors. 12 pass.
[2024-07-09T11:02:17.790+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-07-09T11:02:17.792+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callunyrs5e5/script.py", line 48, in <module>
[2024-07-09T11:02:17.794+0000] {process_utils.py:190} INFO -     res = audit_labeled_transactions(*arg_dict["args"], **arg_dict["kwargs"])
[2024-07-09T11:02:17.795+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callunyrs5e5/script.py", line 21, in audit_labeled_transactions
[2024-07-09T11:02:17.796+0000] {process_utils.py:190} INFO -     check(scan_name, checks_subpath, data_source)
[2024-07-09T11:02:17.797+0000] {process_utils.py:190} INFO -   File "/opt/airflow/include/soda/helpers.py", line 22, in check
[2024-07-09T11:02:17.798+0000] {process_utils.py:190} INFO -     raise ValueError('Soda Scan failed')
[2024-07-09T11:02:17.799+0000] {process_utils.py:190} INFO - ValueError: Soda Scan failed
[2024-07-09T11:02:17.882+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 861, in execute_callable
    return self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Soda Scan failed
[2024-07-09T11:02:17.891+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=audit_labeled_transactions, execution_date=20240709T105955, start_date=20240709T110212, end_date=20240709T110217
[2024-07-09T11:02:17.915+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 183 for task audit_labeled_transactions (Process returned non-zero exit status 1.
Soda Scan failed; 4850)
[2024-07-09T11:02:17.928+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T11:02:17.967+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
